import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE,
} from '@/constants/navigation.constant'
import { ADMIN, OPERATOR, SELLER, USER } from '@/constants/roles.constant'

import type { NavigationTree } from '@/@types/navigation'

const navigationConfig: NavigationTree[] = [
    {
        key: 'dashboardGroup',
        path: '',
        title: 'پنل ادمین',
        translateKey: 'nav.dashboardGroup.title',
        icon: 'groupMenu',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [ADMIN],
        subMenu: [
            {
                key: 'dashboardHome',
                path: '/dashboard',
                title: 'داشبورد',
                translateKey: 'nav.dashboardGroup.home',
                icon: 'home',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN],
                subMenu: [],
            },
        ],
    },
    {
        key: 'websites',
        path: '/websites',
        title: 'وبسایت ها',
        translateKey: 'nav.websites.title',
        icon: 'website',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'sellers',
        path: '/sellers',
        title: ' فروشندگان',
        translateKey: 'nav.sellers.title',
        icon: 'seller',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'categories',
        path: '/categories',
        title: 'دسته بندی ها',
        translateKey: 'nav.categories.title',
        icon: 'category',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'productsList',
        path: '/products-list',
        title: 'محصولات',
        translateKey: 'nav.categories.title',
        icon: 'product',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },


    // {
    //     key: 'siteStats',
    //     path: '',
    //     title: 'آمار سایت',
    //     translateKey: 'nav.siteStats.title',
    //     icon: 'state',
    //     type: NAV_ITEM_TYPE_COLLAPSE,
    //     authority: [],
    //     subMenu: [
    //         {
    //             key: 'registrationChart',
    //             path: '/stats/registration-chart',
    //             title: 'نمودار ثبت نام',
    //             translateKey: 'nav.siteStats.registrationChart',
    //             icon: 'users',
    //             type: NAV_ITEM_TYPE_ITEM,
    //             authority: [],
    //             subMenu: [],
    //         },
    //         {
    //             key: 'subscriptionChart',
    //             path: '/stats/subscription-chart',
    //             title: 'نمودار فروش اشتراک',
    //             translateKey: 'nav.siteStats.subscriptionChart',
    //             icon: 'product',
    //             type: NAV_ITEM_TYPE_ITEM,
    //             authority: [],
    //             subMenu: [],
    //         },
    //         {
    //             key: 'visitChart',
    //             path: '/stats/visit-chart',
    //             title: 'نمودار بازدید',
    //             translateKey: 'nav.siteStats.visitChart',
    //             icon: 'state',
    //             type: NAV_ITEM_TYPE_ITEM,
    //             authority: [],
    //             subMenu: [],
    //         },
    //     ],
    // },
    {
        key: 'monitoring',
        path: '',
        title: 'مانیتورینگ',
        translateKey: 'nav.monitoring.title',
        icon: 'monitoring',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'crawlerService',
                path: '/monitoring/crawler-service',
                title: 'سرویس کرالر',
                translateKey: 'nav.monitoring.crawlerService',
                icon: 'crawler',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'healthTest',
                path: '/monitoring/health-test',
                title: 'تست سلامت ',
                translateKey: 'nav.monitoring.healthTest',
                icon: 'health',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            }

        ],
    },
    {
        key: 'users',
        path: '',
        title: 'کاربران',
        translateKey: 'nav.users.title',
        icon: 'users',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'usersList',
                path: '/users-list',
                title: 'لیست کاربران',
                translateKey: 'nav.users.usersList',
                icon: 'users',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'newUser',
                path: '/users/newUser',
                title: 'افزودن کاربر',
                translateKey: 'nav.users.newUser',
                icon: 'users',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },

        ],
    },
    {
        key: 'settings',
        path: '',
        title: 'تنظیمات',
        translateKey: 'nav.settings.title',
        icon: 'setting',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'crawlerSettings',
                path: '/settings/crawler',
                title: 'تنظیمات کرالر',
                translateKey: 'nav.settings.crawler',
                icon: 'crawler',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
           
            {
                key: 'websiteSettings',
                path: '/settings/website',
                title: 'تنظیمات وبسایت',
                translateKey: 'nav.settings.website',
                icon: 'website',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
]


export default navigationConfig
